name: Deploy to ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  ECR_FRONTEND: 106500537252.dkr.ecr.us-east-2.amazonaws.com/devops-challenge-frontend
  ECR_BACKEND: 106500537252.dkr.ecr.us-east-2.amazonaws.com/devops-challenge-backend
  CLUSTER_NAME: devops-challenge-cluster
  FRONTEND_SVC: devops-challenge-frontend-service
  BACKEND_SVC: devops-challenge-backend-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::106500537252:role/githubactions_ecs_ecr
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push frontend image
        run: |
          docker build -t frontend:latest ./frontend
          docker tag frontend:latest $ECR_FRONTEND:latest
          docker push $ECR_FRONTEND:latest

      - name: Build, tag, and push backend image
        run: |
          docker build -t backend:latest ./backend
          docker tag backend:latest $ECR_BACKEND:latest
          docker push $ECR_BACKEND:latest

      - name: Update ECS frontend service
        run: |
          aws ecs update-service --cluster $CLUSTER_NAME --service $FRONTEND_SVC --force-new-deployment --region $AWS_REGION

      - name: Update ECS backend service
        run: |
          aws ecs update-service --cluster $CLUSTER_NAME --service $BACKEND_SVC --force-new-deployment --region $AWS_REGION
